cookiesList = [
    "Until the life you love, you live... love life, you cannot.",
    "Do or do not. There is no 'maybe'.",
    "Hungry you are. Another cookie, you seek.",
    "Patience you must have, for your lucky numbers to win.",
    "A surprise gift, coming your way it is. Yes, hmmm.",
    "Fear leads to anger. Anger leads to... indigestion.",
    "Great disturbance in the Force... if you do not smile today.",
    "Traveling soon, you are. Pack light, you must.",
    "The love you seek, seeking you it is.",
    "Judge me by my size, do you? Judge your problems by size, do not.",
    "Empty, your mind must be. Then, dessert you may have.",
    "A promotion, I foresee. Work hard, you must.",
    "The Dark Side of the cookie... tasty it is not.",
    "Listen to your elders, you should. Know things, they do.",
    "Confusing, the future is. But bright, yours looks.",
    "Beware the person who hugs too tight. Let go, they will not.",
    "Powerful you have become. The laundry, do you now must.",
    "Your lucky color, green it is. Obviously.",
    "A new friend, waiting around the corner is.",
    "Avoid the path of least resistance. Boring, it is.",
    "Trust your feelings. Say they do: 'Eat more', hmmm?",
    "Much to learn, you still have. Another fortune, buy you must.",
    "Adventure. Excitement. A Jedi craves not these things... but you will have them.",
    "Good relations with the Wookiees, I have. Good relations with your in-laws, have you?",
    "Nap time, highly recommended it is.",
    "If a door closes, open a window you must.",
    "Your wallet... lighter it will become. But your heart, heavier with joy.",
    "Speak like this all day, you will. Annoy your friends, you might.",
    "Lost, your keys are not. Where you left them, they are.",
    "True strength, from within it flows. Also from coffee.",
    "An unexpected visitor, arrive shortly will. Clean your house, you should.",
    "Share your wealth, you must. Or at least, share your fries.",
    "Not the fortune you are looking for, this is. Move along.",
    "Control, control, you must learn control! Especially around chocolate.",
    "A great weight, lifted from your shoulders will be.",
    "Difficult to see. Always in motion is the future. But Tuesday looks good."
]